 name: "portfolio-hf"
 
 on:
      push:
            branches: [master]

 jobs:
      build:
            runs-on: ubuntu-latest
            
            steps:
             - name: Checkout repo
               uses: actions/checkout@v2

             - name: Node setup
               uses: actions/setup-node@v1
               with:
                  node-version: 12
                  
             - name: Configure AWS
               uses: aws-actions/configure-aws-credentials@v1
               with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
                  aws-region: EU (London) eu-west-2
                  
             - name: npm install
               run: npm 

             - name: build
               run: STAGE=dev npm run build

             - name: copy files to s3
               run: aws s3 sync ./dist s3://portfolio-hf
               
             - name: Invalidate cache
               run: |
                aws cloudfront create-invalidation \
                 --distribution-id **HERE** \ 
                 --paths "/*"


               
               